[package]
name = "migrator"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = "0.8.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[dev-dependencies]
pretty_assertions = "1.4.1"
